### ISSUE TITLE
Allow to set threads number, sleep interval and queue size for worker

### ISSUE THREAD

**Issue by shvetsovdm** [shvetsovdm/yabeda-datadog#7]
`Yabeda::Datadog::Worker` has a number of constants: `NUM_THREADS`, `SLEEP_INTERVAL`, `QUEUE_SIZE`. The values of this constants will not work for every usage of the gem. If we allow setting this values on start or via environment variables will solve the issue.

**Comment by Neyaz** [comment]
I think it would be many environment variables for gem's configuration.
I spoke with @Envek about environment variables issue when i worked on my gem and he proposes to use anyway_config gem for that. 
What do you think about it?

**Comment by shvetsovdm** [comment]
@Neyaz sounds good!

**Comment by shvetsovdm** [comment]
solved in 8be34ae09035f6f37d24d5ce51e74d38e2530df3
